### ISSUE TITLE
Filtering bad assemblies

### ISSUE THREAD

**Issue by noahaus** [salvadorlab/Bovis-PangenomeOfReservoirs#2]
_May 14th_

I was able to generate statistics of the genome assembly quality using QUAST. for the most part the data looks good. using the R command summary(), I do find that there are assemblies that are outside the feasible range of being an appropriate M. bovis isolate.

I want to trim the dataset based on the information given in the summary() function. I want to keep all data above the first quantile, but also below the third quantile. This is pretty conservative, but how can I know the appropriate filters on the data?

I want to do this for the attributes for N50, genome length, GC Content, and genome mapping fraction. To me, these are the signs of a good assembly.

![image](https://user-images.githubusercontent.com/40697188/81982883-77a9bb00-9600-11ea-8847-36ef5fdfd3b9.png)

**Comment by noahaus** [comment]
for metrics like N50 & genome fraction, the higher the better, so maybe just cutting off the lowest quantile will be sufficient. Other metrics for computing the IQR then getting the range encompossed in that is good for GC and genome length.

**Comment by noahaus** [comment]
_May 15th_

These values, the higher the better. Where do 5% of the lowest values start?
N50 5% quantile: **46069.75**
Genome Fraction 5% quantile: **97.84405**

These values can take higher and lower ranges, where going too high or low could be considered problematic. For these, set the boundaries with 1.5*IQR below the 1st quantile and above the 3rd quantile.
GC: 
3rd quantile - 1st quantile -> 65.61 - 65.49 -> 0.12
1.5 * iqr -> 1.5 * 0.12 -> 0.18
65.49 - 0.18 > x > 65.61 + 0.18 or **65.31 > x > 65.79**

Total Length: 
3rd quantile - 1st quantile -> 4311607 - 4291430 -> 20177
1.5 * iqr -> 1.5 * 20177 -> 30265.5
4291430 - 30265.5 > x > 4311607 + 30265.5 or **4261165 > x > 4341873**

**Comment by noahaus** [comment]
These are the distributions after applying the filters. These look good to me, but am I missing anything??? I think this is enough to choose the genomes that make it to the next step, I don't want to spend too much time on this.

![image](https://user-images.githubusercontent.com/40697188/82069408-4208de80-96a1-11ea-941c-f4b4bc7d4a09.png)

**Comment by noahaus** [comment]
I also checked how this filtering would impact what metadata we have. With a sigh of relief, I think it impacts it minimally! We shorten our number of isolates from 782 to 621 (might be a blessing, can make computational time shorter too).

![image](https://user-images.githubusercontent.com/40697188/82073191-e7728100-96a6-11ea-84c7-7b1c3f6437e1.png)

**Comment by noahaus** [comment]
In https://www.nature.com/articles/s41598-020-58398-5 they said this about trimming using trimmomatic: 

_Quality trimming and filtering of Illumina reads were performed using the Trimmomatic v0.36 by cutting reads whose average quality falls below an average PHRED score of 20 in a 4 bp sliding window and retaining reads with minimum length of 36 bp_

Could go back and redo the read trimming step and update the command.

**Comment by lsalvador** [comment]
> In https://www.nature.com/articles/s41598-020-58398-5 they said this about trimming using trimmomatic:
> 
> _Quality trimming and filtering of Illumina reads were performed using the Trimmomatic v0.36 by cutting reads whose average quality falls below an average PHRED score of 20 in a 4 bp sliding window and retaining reads with minimum length of 36 bp_
> 
> Could go back and redo the read trimming step and update the command.

I would compare with your current trimming PHRED values and if necessary, repeat trimming analysis
